* Introduction

This is a very simple hack that does a very simple thing.

Have you ever found yourself browing a page for a book on http://flipkart.com/ and, having not enough reviews for it want to checkout the amazon page for the same book - just to get a sense of the book? To do that you would have to open a new tab and then go to amazon.com and then search for this book.  This hack reduces all of this extra effort and reduces to a single click 

* Installation

Currently it is not available on the chrome extension webpage. The only way to install it is to do the following:

1. download the source code
2. In Chrome, open Settings -> Extensions -> Load Unpacked Extensions (and select the just downloaded directory)

Now you are all set.

* How to use it

After installing the chrome extension, when you are on a flipkart.com Book page, you can right click anywhere on the page to find a "Search Amazon for this book" - select that option and you will open a new tab with the amazon page for that book

On any flipkart book if you find a link to a book, you can right click on that link (without having to open that page first), and you will find the same Search Amazon for this book" option described above. The option should work as you would expect it to.

* Limitations and such

- This works only in Chrome, :)

- If the page or link you "lookup" does not correspond to a book, you may still get some - but arbitrary - amazon page
